/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/game/Mountain1.glb");
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={[300, 300, 300]}
      position={[550, 20, -500]}
      rotation={[0, Math.PI, 0]}
    >
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat10} />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes["Node-Mesh_2"].geometry}
        material={materials.mat21}
      />
    </group>
  );
}

useGLTF.preload("/game/Mountain1.glb");
