/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, Instances, Instance } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import state from "ThreeDGame_page/appState";
import { useSnapshot } from "valtio";

const STARTZ = -1150;

const createData = (startZ) => {
  startZ *= 1.2;
  let policeCarsData = [];
  for (let i = 0; i < 12; i++) {
    let obj = {};
    obj["x"] = [-12, 12][Math.round(Math.random())];
    obj["y"] = -2;
    obj["z"] = startZ;
    startZ += 100;
    policeCarsData.push(obj);
  }
  return policeCarsData;
};

const policeCarsData = createData(STARTZ);

export default function PoliceCars({ speed }) {
  const { nodes, materials } = useGLTF("/game/policeCar.glb");

  return (
    <Instances
      geometry={nodes.Police_Car.geometry}
      material={materials.Mat}
      limit={15}
    >
      {policeCarsData.map((pos, i) => (
        <PoliceCar key={i} position={[pos.x, pos.y, pos.z]} speed={speed} />
      ))}
    </Instances>
  );
}

function PoliceCar({ speed, ...props }) {
  const ref = useRef();
  const snap = useSnapshot(state);

  useFrame(() => {
    if (!snap.gameStart) return null;
    let sportsCarPosX = snap.sportsCarPosX;

    if (ref.current.position.z >= 50) {
      ref.current.position.z = STARTZ;
      ref.current.position.x = [-12, 12][Math.round(Math.random())];
    } else {
      ref.current.position.z += speed;
    }

    if (ref.current.position.z > -24 && ref.current.position.z < 32) {
      if (Math.abs(ref.current.position.x - sportsCarPosX) <= 12) {
        state.gameStart = false;
      }
    }
  });

  return <Instance ref={ref} scale={[0.3, 0.3, 0.3]} {...props} />;
}
useGLTF.preload("/game/policeCar.glb");
